language: java

sudo: false

jdk:
#  - openjdk7
  - oraclejdk8

os:
  - linux

script:
# Compile the clapi
  - cd clapi
  - mvn verify
  - mvn compile
  - mvn package
  - cd ..
# Compile the coreserver
  - mvn install:install-file -Dfile=../clapi/clapi.jar -DgroupId=com.clapi -DartifactId=clapi -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true
  - cd coreserver
  - mvn verify
  - mvn compile
  - cd ..
