language: java

sudo: false

jdk:
#  - openjdk7
  - oraclejdk8

os:
  - linux

script:
  # compile clapi
  cd clapi
  mvn verify
  mvn compile
  cd ..
  
  # compile coreserver
  cd coreserver
  mvn verify
  mvn compile
  cd ..
