language: java
sudo: true
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jdk:
- oraclejdk8
os:
- linux
before_install:
  - sudo apt-get install -y graphviz
  - pip install --user codecov
after_success:
  - codecov
script:
- cd clapi
- mvn test
- mvn install
- mvn javadoc:javadoc
- cd ..
- cd coreserver
- mvn compile
- mvn javadoc:javadoc
- cd ..
- utility/publishJavadoc.sh
env:
  global:
    secure: dOaGvT5V/OcE22UOn/a3TGKyLHiU9UWaXr/VhAmqRIPXaTwCBt3wEBr7sA5bE/WUgp8UGaBI7QIx1m9rIeq0Y3tI5FWu2mCz959Sen3rzVBu6x80B+aXmKlSvS9BkYDsDBa4UqRZjxIRSoGrMIHGnoqmRY2twH57tfaalfu/BUsH0Ej4CRVK8fUVzvCWo3caavxaLziqEN9bqKQJqI3kgkJrl910HDRtjmTA5LzYWeRX4WLfqc6YzHvgCO/ktVoGytPGBeB0X2awCnmLa371geMtYM/rJdF6vQxaoZleVqo7DTRAEHUnIe2gCL4LvtrK9YOms205YoMQyJiRCNlPHXxefVUMi8ofpOZ/oECRDu+wu0LIn/qz8BbhPSKTCoSpJ3+qSjskhbLWFEKjOAasnA/tdodzAISW9MjBrUt6svnP5r1AcBq4chAWgYHuH9KqtaFXhY5bjZz+JAn2FopswuwxZb0tW6wUxly5aQLyw9Lcv/RffLmSu+KdKn9uzr6Q/kqGZ6fq3Cm8MHyF6OBeFQ5DK8dyImXJHN80F3Wx4PKI9kVLi+CuCekLQ2cPe2I5DmqGnHQLdSySJkPeFw2UHDIVCzffAzfvxyQz8QXffoexzMGgBgVTmdYXRB0v+fAN6O7sbD0dncUcjMHc/NDTWfxOlZ0JAk4MO+6SZJDgSdo=
