/**
 *  Accessory.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

import java.util.List;

/**
 * Accessory.
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Accessory {

	/**
	 * Enum AccessoryType
	 * 
	 * @author ericpinet
	 * <br> 2015-11-08
	 */
	public enum AccessoryType {
		LIGHT,
		LIGHT_DIMMABLE,
		LIGHT_COLORED,
		LIGHT_COLORED_DIMMABLE,
		FAN,
		AUTOMATIC_DOOR,
		LOCK_MECHANISM,
		THERMOSTAT,
		SWITCH,
		CONTROL_BOARD,
		CAM,
	}
	
	/**
	 * UID of the accessory generated by the server.
	 */
	private String uid;
	
	/**
	 * Label for the accessory.
	 */
	private String label;
	
	/**
	 * Manufacturer for the accessory.
	 */
	private String manufacturer;
	
	/**
	 * Model of the accessory.
	 */
	private String model;
	
	/**
	 * Serial number of the accessory.
	 */
	private String serialnumber;
	
	/**
	 * List of services of the accessory.
	 */
	private List<Service> services;
	
	/**
	 * Image url of the accessory.
	 */
	private String imageurl;

	/**
	 * Default constructor.
	 * 
	 * @param uid
	 * @param label
	 * @param manufacturer
	 * @param model
	 * @param serialnumber
	 * @param services
	 * @param imageurl
	 */
	public Accessory(String uid, String label, String manufacturer, String model, String serialnumber, List<Service> services,
			String imageurl) {
		super();
		this.uid = uid;
		this.label = label;
		this.manufacturer = manufacturer;
		this.model = model;
		this.serialnumber = serialnumber;
		this.services = services;
		this.imageurl = imageurl;
	}
	
	/**
	 * Default constructor.
	 * 
	 * @param uid
	 * @param label
	 */
	public Accessory(String uid, String label) {
		super();
		this.uid = uid;
		this.label = label;
	}

	
	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}


	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}


	/**
	 * @return the label
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * @param label the label to set
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * @return the manufacturer
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * @param manufacturer the manufacturer to set
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	/**
	 * @return the model
	 */
	public String getModel() {
		return model;
	}

	/**
	 * @param model the model to set
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * @return the serialnumber
	 */
	public String getSerialnumber() {
		return serialnumber;
	}

	/**
	 * @param serialnumber the serialnumber to set
	 */
	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}

	/**
	 * @return the services
	 */
	public List<Service> getServices() {
		return services;
	}

	/**
	 * @param services the services to set
	 */
	public void setServices(List<Service> services) {
		this.services = services;
	}

	/**
	 * @return the imageurl
	 */
	public String getImageurl() {
		return imageurl;
	}

	/**
	 * @param imageurl the imageurl to set
	 */
	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}
}
