/**
 *  Asset.java
 *  clapi
 *
 *  Created by ericpinet on 2016-07-08.
 *  Copyright (c) 2016 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

import java.util.List;

/**
 * Asset objects of the system. This object represent a file in system data. (Image, file) 
 * This file can be generated by the system or the user.
 * 
 * @author ericpinet
 * <br> 2016-07-08
 */
public class Asset extends DataObjDefault implements DataObj {

	/**
	 * Enum AssetType
	 * 
	 * @author ericpinet
	 * <br> 2016-07-08
	 */
	public enum AssetType {
		IMAGE,
		FILE,
		OTHER	
	}
	
	/**
	 * Enum AssetMode
	 * 
	 * @author ericpinet
	 * <br> 2016-07-08
	 */
	public enum AssetMode {
		SYSTEM,
		USER	
	}
	
	/**
	 * UID of the asset generated by the server.
	 */
	private String uid;
	
	/**
	 * label of the asset.
	 */
	private String label;
	
	/** 
	 * Type of the asset.
	 */
	private AssetType type;
	
	/** 
	 * Mode of the asset.
	 */
	private AssetMode mode;
	
	/**
	 * Default constructor. 
	 * 
	 * @param uid Uid of the asset.
	 * @param label Label of the asset.
	 * @param type Type of the asset.
	 * @param mode Mode of the asset.
	 */
	public Asset(String uid, String label, AssetType type, AssetMode mode) {
		super();
		this.uid = uid;
		this.label = label;
		this.type = type;
		this.mode = mode;
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * @return the label
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * @param label the label to set
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * @return the type
	 */
	public AssetType getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(AssetType type) {
		this.type = type;
	}

	/**
	 * @return the mode
	 */
	public AssetMode getMode() {
		return mode;
	}

	/**
	 * @param mode the mode to set
	 */
	public void setMode(AssetMode mode) {
		this.mode = mode;
	}

	/**
	 * Return children of this object. 
	 * 
	 * @return Children of this object.
	 * @see com.clapi.data.DataObj#getChildren()
	 */
	@Override
	public List<DataObj> getChildren() {
		return null;
	}

}
