/**
 *  Characteristic.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

/**
 * Characteristic for an accessory service. 
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Characteristic {
	
	/**
	 * Enum CharacteristicAccessMode for a service characteristic.
	 * 
	 * @author ericpinet
	 * <br> 2015-11-08
	 */
	public enum CharacteristicAccessMode {
		READ_ONLY,
		WRITE_ONLY,
		READ_WRITE	
	}
	
	/**
	 * Enum CharacteristicType for a service characteristic.
	 * 
	 * @author ericpinet
	 * <br> 2015-11-08
	 */
	public enum CharacteristicType {
		BOOLEAN,
		ENUM,
		FLOAT,
		INTEGER,
		STATIC_STRING,
		WRITE_ONLY_BOOLEAN
	}
	
	/**
	 * Enum CharacteristicEventType for a service characteristic.
	 * 
	 * @author ericpinet
	 * <br> 2015-11-08
	 */
	public enum CharacteristicEventType {
		NO_EVENT,
		EVENT
	}
	
	/**
	 * UID of the characteristic generated by the server.
	 */
	private String uid;
	
	/**
	 * Access Mode for the characteristic.
	 */
	private CharacteristicAccessMode mode;
	
	/**
	 * Type of the characteristic.
	 */
	private CharacteristicType type;
	
	/**
	 * Indicated if the characteristic is a event.
	 */
	private CharacteristicEventType event;
	
	/**
	 * Data value.
	 */
	private String data;

	/**
	 * Defautl constructor. 
	 * 
	 * @param uid
	 * @param mode
	 * @param type
	 * @param event
	 */
	public Characteristic(String uid, CharacteristicAccessMode mode, CharacteristicType type, CharacteristicEventType event, String data) {
		super();
		this.uid = uid;
		this.mode = mode;
		this.type = type;
		this.event = event;
		this.data = data;
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * @return the mode
	 */
	public CharacteristicAccessMode getMode() {
		return mode;
	}

	/**
	 * @param mode the mode to set
	 */
	public void setMode(CharacteristicAccessMode mode) {
		this.mode = mode;
	}

	/**
	 * @return the type
	 */
	public CharacteristicType getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(CharacteristicType type) {
		this.type = type;
	}

	/**
	 * @return the event
	 */
	public CharacteristicEventType getEvent() {
		return event;
	}

	/**
	 * @param event the event to set
	 */
	public void setEvent(CharacteristicEventType event) {
		this.event = event;
	}

	/**
	 * @return the data
	 */
	public String getData() {
		return data;
	}

	/**
	 * @param data the data to set
	 */
	public void setData(String data) {
		this.data = data;
	}
	
}
