/**
 *  Home.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

import java.util.List;

/**
 * Home.
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Home implements DataObj {
	
	/**
	 * UID of the home generated by the server.
	 */
	private String uid;
	
	/**
	 * Label of the home.
	 */
	private String label;
	
	/**
	 * List of zones in the home.
	 */
	private List<Zone> zones;
	
	/**
	 * Image url of the home.
	 */
	private String imageurl;

	/**
	 * Default constructor. 
	 * 
	 * @param uid Uid of the home.
	 * @param label Label of the home.
	 * @param zones Zones of the home.
	 * @param imageurl ImageURL of the home.
	 */
	public Home(String uid, String label, List<Zone> zones, String imageurl) {
		super();
		this.uid = uid;
		this.label = label;
		this.zones = zones;
		this.imageurl = imageurl;
	}
	
	/**
	 * Default constructor. 
	 * 
	 * @param uid Uid of the home.
	 * @param label Label of the home.
	 */
	public Home(String uid, String label) {
		super();
		this.uid = uid;
		this.label = label;
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * @return the label
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * @param label the label to set
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * @return the zones
	 */
	public List<Zone> getZones() {
		return zones;
	}

	/**
	 * @param zones the zones to set
	 */
	public void setZones(List<Zone> zones) {
		this.zones = zones;
	}

	/**
	 * @return the imageurl
	 */
	public String getImageurl() {
		return imageurl;
	}

	/**
	 * @param imageurl the imageurl to set
	 */
	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}
	
	/**
	 * Return the children of this object.
	 * 
	 * @return Children of this object.
	 * @see com.clapi.data.DataObj#getChildren()
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<DataObj> getChildren() {
		return (List<DataObj>)(Object)getZones();
	}
}