/**
 *  Phone.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

/**
 * Phone number.
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Phone {
	
	/**
	 * Enum PhoneType
	 * 
	 * @author ericpinet
	 * <br> 2015-11-08
	 */
	public enum PhoneType {
		HOME,
		WORK,
		CELL,
		OTHER	
	}
	
	/**
	 * UID of the phone generated by the server.
	 */
	private String uid;
	
	/**
	 * Phone number.
	 */
	private String phone;
	
	/**
	 * Phone Type.
	 */
	private PhoneType type;

	/**
	 * Default constructor. 
	 * 
	 * @param uid
	 * @param phone
	 * @param type
	 */
	public Phone(String uid, String phone, PhoneType type) {
		super();
		this.uid = uid;
		this.phone = phone;
		this.type = type;
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * @return the phone
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * @param phone the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @return the type
	 */
	public PhoneType getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(PhoneType type) {
		this.type = type;
	}
}
