/**
 *  Service.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

import java.util.List;
import java.util.Vector;

/**
 * Service for an accessory.
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Service extends DataObjDefault implements DataObj {
	
	/**
	 * UID of the service generated by the server.
	 */
	private String uid;
	
	/**
	 * Name of the service.
	 */
	private String name;
	
	/**
	 * List of characteristics in the accessory service.
	 */
	private List<Characteristic> characteristics;

	/**
	 * Default constructor. 
	 * 
	 * @param uid Uid of the service.
	 * @param name Name of the service.
	 * @param characteristics Characteristics of the service.
	 */
	public Service(String uid, String name, List<Characteristic> characteristics) {
		super();
		this.uid = uid;
		this.name = name;
		this.characteristics = characteristics;
	}
	
	/**
	 * Default constructor. 
	 * 
	 * @param uid Uid of the service.
	 * @param name of the service.
	 */
	public Service(String uid, String name) {
		super();
		this.uid = uid;
		this.name = name;
		this.characteristics = new Vector<Characteristic>();
		
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the characteristics
	 */
	public List<Characteristic> getCharacteristics() {
		return characteristics;
	}

	/**
	 * @param characteristics the characteristics to set
	 */
	public void setCharacteristics(List<Characteristic> characteristics) {
		this.characteristics = characteristics;
	}
	
	/**
	 * @param characteristic the characteristic to add
	 */
	public void addCharacteristic(Characteristic characteristic) {
		this.characteristics.add(characteristic);
	}

	/**
	 * Return the children of this object.
	 * 
	 * @return Children of this object.
	 * @see com.clapi.data.DataObj#getChildren()
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<DataObj> getChildren() {
		return (List<DataObj>)(Object)getCharacteristics();
	}
}
