/**
 *  Service.java
 *  clapi
 *
 *  Created by ericpinet on 2015-11-08.
 *  Copyright (c) 2015 ConnectLife (Eric Pinet). All rights reserved.
 *
 */
package com.clapi.data;

import java.util.List;

/**
 * Service for an accessory.
 * 
 * @author ericpinet
 * <br> 2015-11-08
 */
public class Service {
	
	/**
	 * UID of the service generated by the server.
	 */
	private String uid;
	
	/**
	 * List of characteristics in the accessory service.
	 */
	private List<Characteristic> characteristics;

	/**
	 * Default constructor. 
	 * 
	 * @param uid
	 * @param characteristics
	 */
	public Service(String uid, List<Characteristic> characteristics) {
		super();
		this.uid = uid;
		this.characteristics = characteristics;
	}
	
	/**
	 * Default constructor. 
	 * 
	 * @param uid
	 */
	public Service(String uid) {
		super();
		this.uid = uid;
	}

	/**
	 * @return the uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * @return the characteristics
	 */
	public List<Characteristic> getCharacteristics() {
		return characteristics;
	}

	/**
	 * @param characteristics the characteristics to set
	 */
	public void setCharacteristics(List<Characteristic> characteristics) {
		this.characteristics = characteristics;
	}
}
