// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface AddEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.AddEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid_person = 1;</code>
   */
  boolean hasUidPerson();
  /**
   * <code>required string uid_person = 1;</code>
   */
  java.lang.String getUidPerson();
  /**
   * <code>required string uid_person = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidPersonBytes();

  /**
   * <code>required string email = 2;</code>
   */
  boolean hasEmail();
  /**
   * <code>required string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>required string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>required int32 type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required int32 type = 3;</code>
   */
  int getType();
}
