// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface AddPersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.AddPersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string firstname = 1;</code>
   */
  boolean hasFirstname();
  /**
   * <code>required string firstname = 1;</code>
   */
  java.lang.String getFirstname();
  /**
   * <code>required string firstname = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>optional string lastname = 2;</code>
   */
  boolean hasLastname();
  /**
   * <code>optional string lastname = 2;</code>
   */
  java.lang.String getLastname();
  /**
   * <code>optional string lastname = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>optional string imageurl = 3;</code>
   */
  boolean hasImageurl();
  /**
   * <code>optional string imageurl = 3;</code>
   */
  java.lang.String getImageurl();
  /**
   * <code>optional string imageurl = 3;</code>
   */
  com.google.protobuf.ByteString
      getImageurlBytes();
}
