// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .clapi.Address.AddressType type = 1 [default = PERSONAL];</code>
   *
   * <pre>
   * type
   * </pre>
   */
  boolean hasType();
  /**
   * <code>optional .clapi.Address.AddressType type = 1 [default = PERSONAL];</code>
   *
   * <pre>
   * type
   * </pre>
   */
  com.clapi.Address.AddressType getType();

  /**
   * <code>required string street = 2;</code>
   *
   * <pre>
   * Street
   * </pre>
   */
  boolean hasStreet();
  /**
   * <code>required string street = 2;</code>
   *
   * <pre>
   * Street
   * </pre>
   */
  java.lang.String getStreet();
  /**
   * <code>required string street = 2;</code>
   *
   * <pre>
   * Street
   * </pre>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>required string city = 3;</code>
   *
   * <pre>
   * City
   * </pre>
   */
  boolean hasCity();
  /**
   * <code>required string city = 3;</code>
   *
   * <pre>
   * City
   * </pre>
   */
  java.lang.String getCity();
  /**
   * <code>required string city = 3;</code>
   *
   * <pre>
   * City
   * </pre>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>required string region = 4;</code>
   *
   * <pre>
   * Region
   * </pre>
   */
  boolean hasRegion();
  /**
   * <code>required string region = 4;</code>
   *
   * <pre>
   * Region
   * </pre>
   */
  java.lang.String getRegion();
  /**
   * <code>required string region = 4;</code>
   *
   * <pre>
   * Region
   * </pre>
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>required string zipcode = 5;</code>
   *
   * <pre>
   * Zip Code
   * </pre>
   */
  boolean hasZipcode();
  /**
   * <code>required string zipcode = 5;</code>
   *
   * <pre>
   * Zip Code
   * </pre>
   */
  java.lang.String getZipcode();
  /**
   * <code>required string zipcode = 5;</code>
   *
   * <pre>
   * Zip Code
   * </pre>
   */
  com.google.protobuf.ByteString
      getZipcodeBytes();

  /**
   * <code>required string country = 6;</code>
   *
   * <pre>
   * Country
   * </pre>
   */
  boolean hasCountry();
  /**
   * <code>required string country = 6;</code>
   *
   * <pre>
   * Country
   * </pre>
   */
  java.lang.String getCountry();
  /**
   * <code>required string country = 6;</code>
   *
   * <pre>
   * Country
   * </pre>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
