// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface CharacteristicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.Characteristic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the characteristic
   * </pre>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the characteristic
   * </pre>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the characteristic
   * </pre>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>required .clapi.Characteristic.CharacteristicAccessMode mode = 2;</code>
   *
   * <pre>
   * Access mode for this characteristic
   * </pre>
   */
  boolean hasMode();
  /**
   * <code>required .clapi.Characteristic.CharacteristicAccessMode mode = 2;</code>
   *
   * <pre>
   * Access mode for this characteristic
   * </pre>
   */
  com.clapi.Characteristic.CharacteristicAccessMode getMode();

  /**
   * <code>required .clapi.Characteristic.CharacteristicType type = 3;</code>
   *
   * <pre>
   * Type of this characteristic
   * </pre>
   */
  boolean hasType();
  /**
   * <code>required .clapi.Characteristic.CharacteristicType type = 3;</code>
   *
   * <pre>
   * Type of this characteristic
   * </pre>
   */
  com.clapi.Characteristic.CharacteristicType getType();

  /**
   * <code>required .clapi.Characteristic.CharacteristicEventType event = 4;</code>
   *
   * <pre>
   * If the characteristic is a event
   * </pre>
   */
  boolean hasEvent();
  /**
   * <code>required .clapi.Characteristic.CharacteristicEventType event = 4;</code>
   *
   * <pre>
   * If the characteristic is a event
   * </pre>
   */
  com.clapi.Characteristic.CharacteristicEventType getEvent();
}
