// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface DeletePhoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.DeletePhoneResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
