// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface DeleteAllPersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.DeleteAllPersonResponse)
    com.google.protobuf.MessageOrBuilder {
}
