// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface NotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.Notification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .clapi.Notification.NotificationType type = 1;</code>
   */
  boolean hasType();
  /**
   * <code>required .clapi.Notification.NotificationType type = 1;</code>
   */
  com.clapi.Notification.NotificationType getType();
}
