// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

/**
 * Protobuf type {@code clapi.Person}
 *
 * <pre>
 * Person
 * </pre>
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:clapi.Person)
    PersonOrBuilder {
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    uid_ = "";
    firstname_ = "";
    lastname_ = "";
    emails_ = java.util.Collections.emptyList();
    phones_ = java.util.Collections.emptyList();
    addresses_ = java.util.Collections.emptyList();
    imageurl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            uid_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            firstname_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            lastname_ = bs;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              emails_ = new java.util.ArrayList<com.clapi.Email>();
              mutable_bitField0_ |= 0x00000008;
            }
            emails_.add(input.readMessage(com.clapi.Email.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              phones_ = new java.util.ArrayList<com.clapi.Phone>();
              mutable_bitField0_ |= 0x00000010;
            }
            phones_.add(input.readMessage(com.clapi.Phone.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              addresses_ = new java.util.ArrayList<com.clapi.Address>();
              mutable_bitField0_ |= 0x00000020;
            }
            addresses_.add(input.readMessage(com.clapi.Address.parser(), extensionRegistry));
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            imageurl_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        emails_ = java.util.Collections.unmodifiableList(emails_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        phones_ = java.util.Collections.unmodifiableList(phones_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        addresses_ = java.util.Collections.unmodifiableList(addresses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clapi.CLApiProtos.internal_static_clapi_Person_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clapi.CLApiProtos.internal_static_clapi_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clapi.Person.class, com.clapi.Person.Builder.class);
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uid_;
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID
   * </pre>
   */
  public boolean hasUid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID
   * </pre>
   */
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        uid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object firstname_;
  /**
   * <code>required string firstname = 2;</code>
   *
   * <pre>
   * First name
   * </pre>
   */
  public boolean hasFirstname() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string firstname = 2;</code>
   *
   * <pre>
   * First name
   * </pre>
   */
  public java.lang.String getFirstname() {
    java.lang.Object ref = firstname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        firstname_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string firstname = 2;</code>
   *
   * <pre>
   * First name
   * </pre>
   */
  public com.google.protobuf.ByteString
      getFirstnameBytes() {
    java.lang.Object ref = firstname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastname_;
  /**
   * <code>required string lastname = 3;</code>
   *
   * <pre>
   * Last name
   * </pre>
   */
  public boolean hasLastname() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string lastname = 3;</code>
   *
   * <pre>
   * Last name
   * </pre>
   */
  public java.lang.String getLastname() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        lastname_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string lastname = 3;</code>
   *
   * <pre>
   * Last name
   * </pre>
   */
  public com.google.protobuf.ByteString
      getLastnameBytes() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAILS_FIELD_NUMBER = 4;
  private java.util.List<com.clapi.Email> emails_;
  /**
   * <code>repeated .clapi.Email emails = 4;</code>
   *
   * <pre>
   * Emails
   * </pre>
   */
  public java.util.List<com.clapi.Email> getEmailsList() {
    return emails_;
  }
  /**
   * <code>repeated .clapi.Email emails = 4;</code>
   *
   * <pre>
   * Emails
   * </pre>
   */
  public java.util.List<? extends com.clapi.EmailOrBuilder> 
      getEmailsOrBuilderList() {
    return emails_;
  }
  /**
   * <code>repeated .clapi.Email emails = 4;</code>
   *
   * <pre>
   * Emails
   * </pre>
   */
  public int getEmailsCount() {
    return emails_.size();
  }
  /**
   * <code>repeated .clapi.Email emails = 4;</code>
   *
   * <pre>
   * Emails
   * </pre>
   */
  public com.clapi.Email getEmails(int index) {
    return emails_.get(index);
  }
  /**
   * <code>repeated .clapi.Email emails = 4;</code>
   *
   * <pre>
   * Emails
   * </pre>
   */
  public com.clapi.EmailOrBuilder getEmailsOrBuilder(
      int index) {
    return emails_.get(index);
  }

  public static final int PHONES_FIELD_NUMBER = 5;
  private java.util.List<com.clapi.Phone> phones_;
  /**
   * <code>repeated .clapi.Phone phones = 5;</code>
   *
   * <pre>
   * Phones
   * </pre>
   */
  public java.util.List<com.clapi.Phone> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .clapi.Phone phones = 5;</code>
   *
   * <pre>
   * Phones
   * </pre>
   */
  public java.util.List<? extends com.clapi.PhoneOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .clapi.Phone phones = 5;</code>
   *
   * <pre>
   * Phones
   * </pre>
   */
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .clapi.Phone phones = 5;</code>
   *
   * <pre>
   * Phones
   * </pre>
   */
  public com.clapi.Phone getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .clapi.Phone phones = 5;</code>
   *
   * <pre>
   * Phones
   * </pre>
   */
  public com.clapi.PhoneOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  public static final int ADDRESSES_FIELD_NUMBER = 6;
  private java.util.List<com.clapi.Address> addresses_;
  /**
   * <code>repeated .clapi.Address addresses = 6;</code>
   *
   * <pre>
   * Address
   * </pre>
   */
  public java.util.List<com.clapi.Address> getAddressesList() {
    return addresses_;
  }
  /**
   * <code>repeated .clapi.Address addresses = 6;</code>
   *
   * <pre>
   * Address
   * </pre>
   */
  public java.util.List<? extends com.clapi.AddressOrBuilder> 
      getAddressesOrBuilderList() {
    return addresses_;
  }
  /**
   * <code>repeated .clapi.Address addresses = 6;</code>
   *
   * <pre>
   * Address
   * </pre>
   */
  public int getAddressesCount() {
    return addresses_.size();
  }
  /**
   * <code>repeated .clapi.Address addresses = 6;</code>
   *
   * <pre>
   * Address
   * </pre>
   */
  public com.clapi.Address getAddresses(int index) {
    return addresses_.get(index);
  }
  /**
   * <code>repeated .clapi.Address addresses = 6;</code>
   *
   * <pre>
   * Address
   * </pre>
   */
  public com.clapi.AddressOrBuilder getAddressesOrBuilder(
      int index) {
    return addresses_.get(index);
  }

  public static final int IMAGEURL_FIELD_NUMBER = 7;
  private volatile java.lang.Object imageurl_;
  /**
   * <code>optional string imageurl = 7;</code>
   *
   * <pre>
   * Image
   * </pre>
   */
  public boolean hasImageurl() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string imageurl = 7;</code>
   *
   * <pre>
   * Image
   * </pre>
   */
  public java.lang.String getImageurl() {
    java.lang.Object ref = imageurl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        imageurl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string imageurl = 7;</code>
   *
   * <pre>
   * Image
   * </pre>
   */
  public com.google.protobuf.ByteString
      getImageurlBytes() {
    java.lang.Object ref = imageurl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageurl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasFirstname()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLastname()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getEmailsCount(); i++) {
      if (!getEmails(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getPhonesCount(); i++) {
      if (!getPhones(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getAddressesCount(); i++) {
      if (!getAddresses(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, firstname_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, lastname_);
    }
    for (int i = 0; i < emails_.size(); i++) {
      output.writeMessage(4, emails_.get(i));
    }
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(5, phones_.get(i));
    }
    for (int i = 0; i < addresses_.size(); i++) {
      output.writeMessage(6, addresses_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, imageurl_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firstname_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, lastname_);
    }
    for (int i = 0; i < emails_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, emails_.get(i));
    }
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, phones_.get(i));
    }
    for (int i = 0; i < addresses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, addresses_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, imageurl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.clapi.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clapi.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clapi.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clapi.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clapi.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.clapi.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.clapi.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.clapi.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.clapi.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.clapi.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clapi.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clapi.Person}
   *
   * <pre>
   * Person
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clapi.Person)
      com.clapi.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clapi.CLApiProtos.internal_static_clapi_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clapi.CLApiProtos.internal_static_clapi_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clapi.Person.class, com.clapi.Person.Builder.class);
    }

    // Construct using com.clapi.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getEmailsFieldBuilder();
        getPhonesFieldBuilder();
        getAddressesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      uid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      firstname_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      lastname_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (emailsBuilder_ == null) {
        emails_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        emailsBuilder_.clear();
      }
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        phonesBuilder_.clear();
      }
      if (addressesBuilder_ == null) {
        addresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        addressesBuilder_.clear();
      }
      imageurl_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clapi.CLApiProtos.internal_static_clapi_Person_descriptor;
    }

    public com.clapi.Person getDefaultInstanceForType() {
      return com.clapi.Person.getDefaultInstance();
    }

    public com.clapi.Person build() {
      com.clapi.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.clapi.Person buildPartial() {
      com.clapi.Person result = new com.clapi.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.uid_ = uid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.firstname_ = firstname_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.lastname_ = lastname_;
      if (emailsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          emails_ = java.util.Collections.unmodifiableList(emails_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.emails_ = emails_;
      } else {
        result.emails_ = emailsBuilder_.build();
      }
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
      if (addressesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.addresses_ = addresses_;
      } else {
        result.addresses_ = addressesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000008;
      }
      result.imageurl_ = imageurl_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clapi.Person) {
        return mergeFrom((com.clapi.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clapi.Person other) {
      if (other == com.clapi.Person.getDefaultInstance()) return this;
      if (other.hasUid()) {
        bitField0_ |= 0x00000001;
        uid_ = other.uid_;
        onChanged();
      }
      if (other.hasFirstname()) {
        bitField0_ |= 0x00000002;
        firstname_ = other.firstname_;
        onChanged();
      }
      if (other.hasLastname()) {
        bitField0_ |= 0x00000004;
        lastname_ = other.lastname_;
        onChanged();
      }
      if (emailsBuilder_ == null) {
        if (!other.emails_.isEmpty()) {
          if (emails_.isEmpty()) {
            emails_ = other.emails_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEmailsIsMutable();
            emails_.addAll(other.emails_);
          }
          onChanged();
        }
      } else {
        if (!other.emails_.isEmpty()) {
          if (emailsBuilder_.isEmpty()) {
            emailsBuilder_.dispose();
            emailsBuilder_ = null;
            emails_ = other.emails_;
            bitField0_ = (bitField0_ & ~0x00000008);
            emailsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEmailsFieldBuilder() : null;
          } else {
            emailsBuilder_.addAllMessages(other.emails_);
          }
        }
      }
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000010);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      if (addressesBuilder_ == null) {
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
      } else {
        if (!other.addresses_.isEmpty()) {
          if (addressesBuilder_.isEmpty()) {
            addressesBuilder_.dispose();
            addressesBuilder_ = null;
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000020);
            addressesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAddressesFieldBuilder() : null;
          } else {
            addressesBuilder_.addAllMessages(other.addresses_);
          }
        }
      }
      if (other.hasImageurl()) {
        bitField0_ |= 0x00000040;
        imageurl_ = other.imageurl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUid()) {
        return false;
      }
      if (!hasFirstname()) {
        return false;
      }
      if (!hasLastname()) {
        return false;
      }
      for (int i = 0; i < getEmailsCount(); i++) {
        if (!getEmails(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getPhonesCount(); i++) {
        if (!getPhones(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getAddressesCount(); i++) {
        if (!getAddresses(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clapi.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clapi.Person) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uid_ = "";
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = getDefaultInstance().getUid();
      onChanged();
      return this;
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID
     * </pre>
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object firstname_ = "";
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public Builder setFirstname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      firstname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public Builder clearFirstname() {
      bitField0_ = (bitField0_ & ~0x00000002);
      firstname_ = getDefaultInstance().getFirstname();
      onChanged();
      return this;
    }
    /**
     * <code>required string firstname = 2;</code>
     *
     * <pre>
     * First name
     * </pre>
     */
    public Builder setFirstnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      firstname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastname_ = "";
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public Builder setLastname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lastname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public Builder clearLastname() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastname_ = getDefaultInstance().getLastname();
      onChanged();
      return this;
    }
    /**
     * <code>required string lastname = 3;</code>
     *
     * <pre>
     * Last name
     * </pre>
     */
    public Builder setLastnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lastname_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.clapi.Email> emails_ =
      java.util.Collections.emptyList();
    private void ensureEmailsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        emails_ = new java.util.ArrayList<com.clapi.Email>(emails_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Email, com.clapi.Email.Builder, com.clapi.EmailOrBuilder> emailsBuilder_;

    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public java.util.List<com.clapi.Email> getEmailsList() {
      if (emailsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(emails_);
      } else {
        return emailsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public int getEmailsCount() {
      if (emailsBuilder_ == null) {
        return emails_.size();
      } else {
        return emailsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public com.clapi.Email getEmails(int index) {
      if (emailsBuilder_ == null) {
        return emails_.get(index);
      } else {
        return emailsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder setEmails(
        int index, com.clapi.Email value) {
      if (emailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailsIsMutable();
        emails_.set(index, value);
        onChanged();
      } else {
        emailsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder setEmails(
        int index, com.clapi.Email.Builder builderForValue) {
      if (emailsBuilder_ == null) {
        ensureEmailsIsMutable();
        emails_.set(index, builderForValue.build());
        onChanged();
      } else {
        emailsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder addEmails(com.clapi.Email value) {
      if (emailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
      } else {
        emailsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder addEmails(
        int index, com.clapi.Email value) {
      if (emailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailsIsMutable();
        emails_.add(index, value);
        onChanged();
      } else {
        emailsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder addEmails(
        com.clapi.Email.Builder builderForValue) {
      if (emailsBuilder_ == null) {
        ensureEmailsIsMutable();
        emails_.add(builderForValue.build());
        onChanged();
      } else {
        emailsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder addEmails(
        int index, com.clapi.Email.Builder builderForValue) {
      if (emailsBuilder_ == null) {
        ensureEmailsIsMutable();
        emails_.add(index, builderForValue.build());
        onChanged();
      } else {
        emailsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder addAllEmails(
        java.lang.Iterable<? extends com.clapi.Email> values) {
      if (emailsBuilder_ == null) {
        ensureEmailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emails_);
        onChanged();
      } else {
        emailsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder clearEmails() {
      if (emailsBuilder_ == null) {
        emails_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        emailsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public Builder removeEmails(int index) {
      if (emailsBuilder_ == null) {
        ensureEmailsIsMutable();
        emails_.remove(index);
        onChanged();
      } else {
        emailsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public com.clapi.Email.Builder getEmailsBuilder(
        int index) {
      return getEmailsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public com.clapi.EmailOrBuilder getEmailsOrBuilder(
        int index) {
      if (emailsBuilder_ == null) {
        return emails_.get(index);  } else {
        return emailsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public java.util.List<? extends com.clapi.EmailOrBuilder> 
         getEmailsOrBuilderList() {
      if (emailsBuilder_ != null) {
        return emailsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(emails_);
      }
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public com.clapi.Email.Builder addEmailsBuilder() {
      return getEmailsFieldBuilder().addBuilder(
          com.clapi.Email.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public com.clapi.Email.Builder addEmailsBuilder(
        int index) {
      return getEmailsFieldBuilder().addBuilder(
          index, com.clapi.Email.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Email emails = 4;</code>
     *
     * <pre>
     * Emails
     * </pre>
     */
    public java.util.List<com.clapi.Email.Builder> 
         getEmailsBuilderList() {
      return getEmailsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Email, com.clapi.Email.Builder, com.clapi.EmailOrBuilder> 
        getEmailsFieldBuilder() {
      if (emailsBuilder_ == null) {
        emailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.clapi.Email, com.clapi.Email.Builder, com.clapi.EmailOrBuilder>(
                emails_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        emails_ = null;
      }
      return emailsBuilder_;
    }

    private java.util.List<com.clapi.Phone> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        phones_ = new java.util.ArrayList<com.clapi.Phone>(phones_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Phone, com.clapi.Phone.Builder, com.clapi.PhoneOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public java.util.List<com.clapi.Phone> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public com.clapi.Phone getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder setPhones(
        int index, com.clapi.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder setPhones(
        int index, com.clapi.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder addPhones(com.clapi.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder addPhones(
        int index, com.clapi.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder addPhones(
        com.clapi.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder addPhones(
        int index, com.clapi.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends com.clapi.Phone> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public com.clapi.Phone.Builder getPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public com.clapi.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public java.util.List<? extends com.clapi.PhoneOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public com.clapi.Phone.Builder addPhonesBuilder() {
      return getPhonesFieldBuilder().addBuilder(
          com.clapi.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public com.clapi.Phone.Builder addPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().addBuilder(
          index, com.clapi.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Phone phones = 5;</code>
     *
     * <pre>
     * Phones
     * </pre>
     */
    public java.util.List<com.clapi.Phone.Builder> 
         getPhonesBuilderList() {
      return getPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Phone, com.clapi.Phone.Builder, com.clapi.PhoneOrBuilder> 
        getPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.clapi.Phone, com.clapi.Phone.Builder, com.clapi.PhoneOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }

    private java.util.List<com.clapi.Address> addresses_ =
      java.util.Collections.emptyList();
    private void ensureAddressesIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        addresses_ = new java.util.ArrayList<com.clapi.Address>(addresses_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Address, com.clapi.Address.Builder, com.clapi.AddressOrBuilder> addressesBuilder_;

    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public java.util.List<com.clapi.Address> getAddressesList() {
      if (addressesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(addresses_);
      } else {
        return addressesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public int getAddressesCount() {
      if (addressesBuilder_ == null) {
        return addresses_.size();
      } else {
        return addressesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public com.clapi.Address getAddresses(int index) {
      if (addressesBuilder_ == null) {
        return addresses_.get(index);
      } else {
        return addressesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder setAddresses(
        int index, com.clapi.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
      } else {
        addressesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder setAddresses(
        int index, com.clapi.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder addAddresses(com.clapi.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
      } else {
        addressesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder addAddresses(
        int index, com.clapi.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.add(index, value);
        onChanged();
      } else {
        addressesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder addAddresses(
        com.clapi.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.add(builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder addAddresses(
        int index, com.clapi.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder addAllAddresses(
        java.lang.Iterable<? extends com.clapi.Address> values) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresses_);
        onChanged();
      } else {
        addressesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder clearAddresses() {
      if (addressesBuilder_ == null) {
        addresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        addressesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public Builder removeAddresses(int index) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.remove(index);
        onChanged();
      } else {
        addressesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public com.clapi.Address.Builder getAddressesBuilder(
        int index) {
      return getAddressesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public com.clapi.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      if (addressesBuilder_ == null) {
        return addresses_.get(index);  } else {
        return addressesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public java.util.List<? extends com.clapi.AddressOrBuilder> 
         getAddressesOrBuilderList() {
      if (addressesBuilder_ != null) {
        return addressesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(addresses_);
      }
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public com.clapi.Address.Builder addAddressesBuilder() {
      return getAddressesFieldBuilder().addBuilder(
          com.clapi.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public com.clapi.Address.Builder addAddressesBuilder(
        int index) {
      return getAddressesFieldBuilder().addBuilder(
          index, com.clapi.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Address addresses = 6;</code>
     *
     * <pre>
     * Address
     * </pre>
     */
    public java.util.List<com.clapi.Address.Builder> 
         getAddressesBuilderList() {
      return getAddressesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Address, com.clapi.Address.Builder, com.clapi.AddressOrBuilder> 
        getAddressesFieldBuilder() {
      if (addressesBuilder_ == null) {
        addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.clapi.Address, com.clapi.Address.Builder, com.clapi.AddressOrBuilder>(
                addresses_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        addresses_ = null;
      }
      return addressesBuilder_;
    }

    private java.lang.Object imageurl_ = "";
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public boolean hasImageurl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public java.lang.String getImageurl() {
      java.lang.Object ref = imageurl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageurl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public com.google.protobuf.ByteString
        getImageurlBytes() {
      java.lang.Object ref = imageurl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public Builder setImageurl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      imageurl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public Builder clearImageurl() {
      bitField0_ = (bitField0_ & ~0x00000040);
      imageurl_ = getDefaultInstance().getImageurl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string imageurl = 7;</code>
     *
     * <pre>
     * Image
     * </pre>
     */
    public Builder setImageurlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      imageurl_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clapi.Person)
  }

  // @@protoc_insertion_point(class_scope:clapi.Person)
  private static final com.clapi.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clapi.Person();
  }

  public static com.clapi.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Person(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  public com.clapi.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

