// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

public interface ServiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.Service)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the service
   * </pre>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the service
   * </pre>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the service
   * </pre>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>repeated .clapi.Characteristic characteristics = 2;</code>
   *
   * <pre>
   * List of Characteristic in this service
   * </pre>
   */
  java.util.List<com.clapi.Characteristic> 
      getCharacteristicsList();
  /**
   * <code>repeated .clapi.Characteristic characteristics = 2;</code>
   *
   * <pre>
   * List of Characteristic in this service
   * </pre>
   */
  com.clapi.Characteristic getCharacteristics(int index);
  /**
   * <code>repeated .clapi.Characteristic characteristics = 2;</code>
   *
   * <pre>
   * List of Characteristic in this service
   * </pre>
   */
  int getCharacteristicsCount();
  /**
   * <code>repeated .clapi.Characteristic characteristics = 2;</code>
   *
   * <pre>
   * List of Characteristic in this service
   * </pre>
   */
  java.util.List<? extends com.clapi.CharacteristicOrBuilder> 
      getCharacteristicsOrBuilderList();
  /**
   * <code>repeated .clapi.Characteristic characteristics = 2;</code>
   *
   * <pre>
   * List of Characteristic in this service
   * </pre>
   */
  com.clapi.CharacteristicOrBuilder getCharacteristicsOrBuilder(
      int index);
}
