// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi;

/**
 * Protobuf type {@code clapi.Zone}
 *
 * <pre>
 * Zone
 * </pre>
 */
public  final class Zone extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:clapi.Zone)
    ZoneOrBuilder {
  // Use Zone.newBuilder() to construct.
  private Zone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Zone() {
    uid_ = "";
    label_ = "";
    rooms_ = java.util.Collections.emptyList();
    imageurl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Zone(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            uid_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            label_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              rooms_ = new java.util.ArrayList<com.clapi.Room>();
              mutable_bitField0_ |= 0x00000004;
            }
            rooms_.add(input.readMessage(com.clapi.Room.parser(), extensionRegistry));
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            imageurl_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        rooms_ = java.util.Collections.unmodifiableList(rooms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clapi.CLApiProtos.internal_static_clapi_Zone_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clapi.CLApiProtos.internal_static_clapi_Zone_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clapi.Zone.class, com.clapi.Zone.Builder.class);
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uid_;
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the zone
   * </pre>
   */
  public boolean hasUid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the zone
   * </pre>
   */
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        uid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string uid = 1;</code>
   *
   * <pre>
   * UID of the zone
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object label_;
  /**
   * <code>required string label = 2;</code>
   *
   * <pre>
   * Label of the zone
   * </pre>
   */
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string label = 2;</code>
   *
   * <pre>
   * Label of the zone
   * </pre>
   */
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        label_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string label = 2;</code>
   *
   * <pre>
   * Label of the zone
   * </pre>
   */
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMS_FIELD_NUMBER = 3;
  private java.util.List<com.clapi.Room> rooms_;
  /**
   * <code>repeated .clapi.Room rooms = 3;</code>
   *
   * <pre>
   * List of rooms in this zone
   * </pre>
   */
  public java.util.List<com.clapi.Room> getRoomsList() {
    return rooms_;
  }
  /**
   * <code>repeated .clapi.Room rooms = 3;</code>
   *
   * <pre>
   * List of rooms in this zone
   * </pre>
   */
  public java.util.List<? extends com.clapi.RoomOrBuilder> 
      getRoomsOrBuilderList() {
    return rooms_;
  }
  /**
   * <code>repeated .clapi.Room rooms = 3;</code>
   *
   * <pre>
   * List of rooms in this zone
   * </pre>
   */
  public int getRoomsCount() {
    return rooms_.size();
  }
  /**
   * <code>repeated .clapi.Room rooms = 3;</code>
   *
   * <pre>
   * List of rooms in this zone
   * </pre>
   */
  public com.clapi.Room getRooms(int index) {
    return rooms_.get(index);
  }
  /**
   * <code>repeated .clapi.Room rooms = 3;</code>
   *
   * <pre>
   * List of rooms in this zone
   * </pre>
   */
  public com.clapi.RoomOrBuilder getRoomsOrBuilder(
      int index) {
    return rooms_.get(index);
  }

  public static final int IMAGEURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object imageurl_;
  /**
   * <code>optional string imageurl = 4;</code>
   *
   * <pre>
   * Image url for this zone
   * </pre>
   */
  public boolean hasImageurl() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string imageurl = 4;</code>
   *
   * <pre>
   * Image url for this zone
   * </pre>
   */
  public java.lang.String getImageurl() {
    java.lang.Object ref = imageurl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        imageurl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string imageurl = 4;</code>
   *
   * <pre>
   * Image url for this zone
   * </pre>
   */
  public com.google.protobuf.ByteString
      getImageurlBytes() {
    java.lang.Object ref = imageurl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageurl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLabel()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getRoomsCount(); i++) {
      if (!getRooms(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, label_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      output.writeMessage(3, rooms_.get(i));
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, imageurl_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, label_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, rooms_.get(i));
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, imageurl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.clapi.Zone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clapi.Zone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clapi.Zone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clapi.Zone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clapi.Zone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.clapi.Zone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.clapi.Zone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.clapi.Zone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.clapi.Zone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.clapi.Zone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clapi.Zone prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clapi.Zone}
   *
   * <pre>
   * Zone
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clapi.Zone)
      com.clapi.ZoneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clapi.CLApiProtos.internal_static_clapi_Zone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clapi.CLApiProtos.internal_static_clapi_Zone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clapi.Zone.class, com.clapi.Zone.Builder.class);
    }

    // Construct using com.clapi.Zone.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRoomsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      uid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      label_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        roomsBuilder_.clear();
      }
      imageurl_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clapi.CLApiProtos.internal_static_clapi_Zone_descriptor;
    }

    public com.clapi.Zone getDefaultInstanceForType() {
      return com.clapi.Zone.getDefaultInstance();
    }

    public com.clapi.Zone build() {
      com.clapi.Zone result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.clapi.Zone buildPartial() {
      com.clapi.Zone result = new com.clapi.Zone(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.uid_ = uid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.label_ = label_;
      if (roomsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.rooms_ = rooms_;
      } else {
        result.rooms_ = roomsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000004;
      }
      result.imageurl_ = imageurl_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clapi.Zone) {
        return mergeFrom((com.clapi.Zone)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clapi.Zone other) {
      if (other == com.clapi.Zone.getDefaultInstance()) return this;
      if (other.hasUid()) {
        bitField0_ |= 0x00000001;
        uid_ = other.uid_;
        onChanged();
      }
      if (other.hasLabel()) {
        bitField0_ |= 0x00000002;
        label_ = other.label_;
        onChanged();
      }
      if (roomsBuilder_ == null) {
        if (!other.rooms_.isEmpty()) {
          if (rooms_.isEmpty()) {
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRoomsIsMutable();
            rooms_.addAll(other.rooms_);
          }
          onChanged();
        }
      } else {
        if (!other.rooms_.isEmpty()) {
          if (roomsBuilder_.isEmpty()) {
            roomsBuilder_.dispose();
            roomsBuilder_ = null;
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000004);
            roomsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRoomsFieldBuilder() : null;
          } else {
            roomsBuilder_.addAllMessages(other.rooms_);
          }
        }
      }
      if (other.hasImageurl()) {
        bitField0_ |= 0x00000008;
        imageurl_ = other.imageurl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUid()) {
        return false;
      }
      if (!hasLabel()) {
        return false;
      }
      for (int i = 0; i < getRoomsCount(); i++) {
        if (!getRooms(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clapi.Zone parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clapi.Zone) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uid_ = "";
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = getDefaultInstance().getUid();
      onChanged();
      return this;
    }
    /**
     * <code>required string uid = 1;</code>
     *
     * <pre>
     * UID of the zone
     * </pre>
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public Builder clearLabel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>required string label = 2;</code>
     *
     * <pre>
     * Label of the zone
     * </pre>
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      label_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.clapi.Room> rooms_ =
      java.util.Collections.emptyList();
    private void ensureRoomsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        rooms_ = new java.util.ArrayList<com.clapi.Room>(rooms_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Room, com.clapi.Room.Builder, com.clapi.RoomOrBuilder> roomsBuilder_;

    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public java.util.List<com.clapi.Room> getRoomsList() {
      if (roomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rooms_);
      } else {
        return roomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public int getRoomsCount() {
      if (roomsBuilder_ == null) {
        return rooms_.size();
      } else {
        return roomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public com.clapi.Room getRooms(int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);
      } else {
        return roomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder setRooms(
        int index, com.clapi.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.set(index, value);
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder setRooms(
        int index, com.clapi.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder addRooms(com.clapi.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder addRooms(
        int index, com.clapi.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(index, value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder addRooms(
        com.clapi.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder addRooms(
        int index, com.clapi.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder addAllRooms(
        java.lang.Iterable<? extends com.clapi.Room> values) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rooms_);
        onChanged();
      } else {
        roomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder clearRooms() {
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public Builder removeRooms(int index) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.remove(index);
        onChanged();
      } else {
        roomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public com.clapi.Room.Builder getRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public com.clapi.RoomOrBuilder getRoomsOrBuilder(
        int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);  } else {
        return roomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public java.util.List<? extends com.clapi.RoomOrBuilder> 
         getRoomsOrBuilderList() {
      if (roomsBuilder_ != null) {
        return roomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rooms_);
      }
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public com.clapi.Room.Builder addRoomsBuilder() {
      return getRoomsFieldBuilder().addBuilder(
          com.clapi.Room.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public com.clapi.Room.Builder addRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().addBuilder(
          index, com.clapi.Room.getDefaultInstance());
    }
    /**
     * <code>repeated .clapi.Room rooms = 3;</code>
     *
     * <pre>
     * List of rooms in this zone
     * </pre>
     */
    public java.util.List<com.clapi.Room.Builder> 
         getRoomsBuilderList() {
      return getRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.clapi.Room, com.clapi.Room.Builder, com.clapi.RoomOrBuilder> 
        getRoomsFieldBuilder() {
      if (roomsBuilder_ == null) {
        roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.clapi.Room, com.clapi.Room.Builder, com.clapi.RoomOrBuilder>(
                rooms_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        rooms_ = null;
      }
      return roomsBuilder_;
    }

    private java.lang.Object imageurl_ = "";
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public boolean hasImageurl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public java.lang.String getImageurl() {
      java.lang.Object ref = imageurl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageurl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public com.google.protobuf.ByteString
        getImageurlBytes() {
      java.lang.Object ref = imageurl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public Builder setImageurl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      imageurl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public Builder clearImageurl() {
      bitField0_ = (bitField0_ & ~0x00000008);
      imageurl_ = getDefaultInstance().getImageurl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string imageurl = 4;</code>
     *
     * <pre>
     * Image url for this zone
     * </pre>
     */
    public Builder setImageurlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      imageurl_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clapi.Zone)
  }

  // @@protoc_insertion_point(class_scope:clapi.Zone)
  private static final com.clapi.Zone DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clapi.Zone();
  }

  public static com.clapi.Zone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Zone>
      PARSER = new com.google.protobuf.AbstractParser<Zone>() {
    public Zone parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Zone(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Zone> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Zone> getParserForType() {
    return PARSER;
  }

  public com.clapi.Zone getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

