// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface AddHomeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.AddHomeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string label = 1;</code>
   */
  boolean hasLabel();
  /**
   * <code>required string label = 1;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>required string label = 1;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>optional string imageurl = 2;</code>
   */
  boolean hasImageurl();
  /**
   * <code>optional string imageurl = 2;</code>
   */
  java.lang.String getImageurl();
  /**
   * <code>optional string imageurl = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageurlBytes();
}
