// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

/**
 * Protobuf enum {@code clapi.AddressType}
 *
 * <pre>
 * Address type
 * </pre>
 */
public enum AddressType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ADDRESS_HOME = 0;</code>
   */
  ADDRESS_HOME(0, 0),
  /**
   * <code>ADDRES_WORK = 1;</code>
   */
  ADDRES_WORK(1, 1),
  /**
   * <code>ADDRES_OTHER = 2;</code>
   */
  ADDRES_OTHER(2, 2),
  ;

  /**
   * <code>ADDRESS_HOME = 0;</code>
   */
  public static final int ADDRESS_HOME_VALUE = 0;
  /**
   * <code>ADDRES_WORK = 1;</code>
   */
  public static final int ADDRES_WORK_VALUE = 1;
  /**
   * <code>ADDRES_OTHER = 2;</code>
   */
  public static final int ADDRES_OTHER_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  public static AddressType valueOf(int value) {
    switch (value) {
      case 0: return ADDRESS_HOME;
      case 1: return ADDRES_WORK;
      case 2: return ADDRES_OTHER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AddressType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AddressType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AddressType>() {
          public AddressType findValueByNumber(int number) {
            return AddressType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.clapi.protocol.CLApiProtos.getDescriptor()
        .getEnumTypes().get(2);
  }

  private static final AddressType[] VALUES = values();

  public static AddressType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private AddressType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clapi.AddressType)
}

