// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface AddRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.AddRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid_zone = 1;</code>
   */
  boolean hasUidZone();
  /**
   * <code>required string uid_zone = 1;</code>
   */
  java.lang.String getUidZone();
  /**
   * <code>required string uid_zone = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidZoneBytes();

  /**
   * <code>required string label = 2;</code>
   */
  boolean hasLabel();
  /**
   * <code>required string label = 2;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>required string label = 2;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>optional string imageuid = 3;</code>
   */
  boolean hasImageuid();
  /**
   * <code>optional string imageuid = 3;</code>
   */
  java.lang.String getImageuid();
  /**
   * <code>optional string imageuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getImageuidBytes();
}
