// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface GetAssertUrlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.GetAssertUrlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string url = 1;</code>
   */
  boolean hasUrl();
  /**
   * <code>required string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>required string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
