// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface UpdateAssetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.UpdateAssetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>required string label = 2;</code>
   */
  boolean hasLabel();
  /**
   * <code>required string label = 2;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>required string label = 2;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>required .clapi.AssetType type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required .clapi.AssetType type = 3;</code>
   */
  com.clapi.protocol.AssetType getType();

  /**
   * <code>required .clapi.AssetMode mode = 4;</code>
   */
  boolean hasMode();
  /**
   * <code>required .clapi.AssetMode mode = 4;</code>
   */
  com.clapi.protocol.AssetMode getMode();

  /**
   * <code>required bytes data = 5;</code>
   */
  boolean hasData();
  /**
   * <code>required bytes data = 5;</code>
   */
  com.google.protobuf.ByteString getData();
}
