// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface UpdatePhoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.UpdatePhoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>required string phone = 2;</code>
   */
  boolean hasPhone();
  /**
   * <code>required string phone = 2;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>required string phone = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>required .clapi.PhoneType type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required .clapi.PhoneType type = 3;</code>
   */
  com.clapi.protocol.PhoneType getType();
}
