// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clapi.proto

package com.clapi.protocol;

public interface WaitNotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clapi.WaitNotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .clapi.Notification notification = 1;</code>
   */
  boolean hasNotification();
  /**
   * <code>required .clapi.Notification notification = 1;</code>
   */
  com.clapi.protocol.Notification getNotification();
  /**
   * <code>required .clapi.Notification notification = 1;</code>
   */
  com.clapi.protocol.NotificationOrBuilder getNotificationOrBuilder();

  /**
   * <code>optional string error = 2;</code>
   */
  boolean hasError();
  /**
   * <code>optional string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
