/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.connectlife.clapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * CharacteristicEventType
 */
public enum CharacteristicEventType implements org.apache.thrift.TEnum {
  NO_EVENT(1),
  EVENT(2);

  private final int value;

  private CharacteristicEventType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CharacteristicEventType findByValue(int value) { 
    switch (value) {
      case 1:
        return NO_EVENT;
      case 2:
        return EVENT;
      default:
        return null;
    }
  }
}
